config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'projects#home'

  resources :projects, except: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    #can :manage, Project, user_id: user.id

    if user.admin?
      can :manage, :all
      #can [:read, :create, :update, :destroy], Project
    else
      can [:read, :create], Project, user_id: user.id
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  belongs_to :user

  validates :name, presence: true
  validates :user_id, presence: true

  scope :order_desc, -> { order('created_at desc') }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]

  has_many :projects, dependent: :destroy

  attr_accessor :phone_number

  def admin?
  	admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_params, if: :devise_controller?

  
  rescue_from CanCan::AccessDenied do |exception|  
    flash[:error] = "Access denied!"  
    redirect_to root_url  
  end 

  protected

  def permission_denied!(ex)
    flash[:alert] = "You are not allowed!"
    redirect_to root_url
  end

  def configure_permitted_params
  	#devise_parameter_sanitizer.for(:sign_up) << :phone_number
  	#devise_parameter_sanitizer.for(:account_update) << :username
    devise_parameter_sanitizer.for(:sign_up) { |s| s.permit(:email, :phone_number, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |a| a.permit(:email, :phone_number, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  def home
    #@projects = current_user.projects
    current_user.admin? ? @projects = Project.order_desc : 
                          @projects = Project.order_desc.accessible_by(current_ability)
  end

  def new
    @project = Project.new
    render :show_form
  end

  def create
    @project = current_user.projects.new(project_params)
    @project.user = current_user
    authorize! :create, @project
    
    save_project
  end

  def edit
  	@project = project_find
    authorize! :edit, @project
  	render :show_form
  end

  def update
    @project = project_find
    @project.assign_attributes(project_params)
    authorize! :update, @project

    save_project    
  end

  def destroy
    @project = project_find.destroy
    @projects = Project.accessible_by(current_ability)
  end

  private

  def project_params
    parameters = [:name]
    parameters << :status if current_user.admin?
    params.require(:project).permit(parameters)
  end

  def project_find
  	Project.find(params[:id])
  end

  def save_project
  	if @project.save
  		@projects = Project.accessible_by(current_ability)
      render :hide_form
  	else
      render :show_form
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <div class = "devise">
    <% if user_signed_in? %>
      <span> Hello, <%= "#{current_user.email}" %> | </span>
      <%= link_to "Log uot", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %> |  
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %>
  </div>
  <title>Roxtudio Partner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  
<div class="row-fluid"> 
  <div class="span10 offset1">     
    <div class="hero-unit text-center">
      <h1>Roxtudio Partner<h1> 
    </div>   
  </div> 
</div>
<div class = "text-center">
  <%= yield %>
</div>
<p class="notice"><%= notice %></p>
<p class="alert-alert"><%= alert %></p>
</body>
</html>

app/views/projects/_project_form.html.erb
<div class = "modal-header">
	<% project.new_record? ? "New project" : "Editing project #{project.name}" %>
  <%= simple_form_for project, remote: true do |p| %>
    <div class = "modal-body">
    	<%= p.input :name, placeholder: "new project" %>
    	<% if current_user.admin? %>
    	  <%= p.input :status %>
    	<% end %>
    	<%= p.submit "Save", class: 'btn-save btn' %>
    </div>
  <% end %>
</div>

app/views/projects/_projects.html.erb
<% if projects.empty? %>
  <span class = "text-warning">
    There are no Projects yet
  </span>
<% else %>
  <table class = "table table-hover table-bordered">
    <thead>
      <tr>
        <th> Project id </th>
        <th> Project name </th>
        <th> Status </th>
        <% if can? [:update, :destroy], projects %>
          <th> Action </th>
        <% end %>
      </tr>
    </thead>

    <br />

    <tbody>
      <% projects.each do |project| %>
        <tr id = "<%= dom_id(project) %>">
          <td> <%= project.id %> </td>
          <td> <%= project.name %></td>
          <td> <%= project.status %></td>
          <% if can? :update, project %>
            <td> <%= link_to edit_project_path(project), remote: true do %>
               <i class = "icon-edit"> </i>
             <% end %>
            </td>
          <% end %>

          <% if can? :destroy, project %>
            <td> <%= link_to project_path(project), remote: true, data: { confirm:    "   Are you sure?" }, method: :delete do %>
                 <i class = "icon-remove"> </i>
               <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <tbody>
  </table>
<% end %>

app/views/projects/create.js.erb
$('#project_list').html('<%= j(render 'projects/projects', projects: @projects) %>');

$('#modal').modal('hide');

app/views/projects/destroy.js.erb
$('#project_list').html('<%= j(render 'projects', projects: @projects) %>');

app/views/projects/hide_form.js.erb
$('#project_list').html('<%= j(render 'projects/projects', projects: @projects) %>');

$('#modal').modal('hide');

app/views/projects/home.html.erb
<div id = "new_btn" class = "btn btn-large" ><%= link_to "New Project", new_project_path, remote: true %>
</div>
<% if current_user.admin? %>
  <b>RIGHT CODE!</b>
<% end %>
<div id = "project_list" class = "container">
  <br />
  <%= render 'projects', projects: @projects %>
</div>
<br />

<div id = "modal" class = "modal fade"> </div>

app/views/projects/new.js.erb
m = $("#modal").html("<%= j(render 'project_form',  project: @project) %>");
m.modal("show");

app/views/projects/show_form.js.erb
m = $("#modal").html("<%= j(render 'project_form', project: @project) %>");
  
m.modal("show");